import type { ChecklistItem, WriteTodoInput } from "@beam-me-up/core";

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

/** The OAuth providers we scaffold auth for (used in Manual setup). */
const OAUTH_PROVIDERS = ["google", "github"] as const;

/**
 * Build the OAuth redirect URI for a provider given the (best-known) live URL.
 * Falls back to a placeholder when liveUrl is not yet known.
 */
function redirectUri(liveUrl: string | undefined, provider: string): string {
  const base = (liveUrl ?? "<your-live-url>").replace(/\/+$/, "");
  return `${base}/api/auth/callback/${provider}`;
}

/**
 * shipChecklist - the ship-checklist items TAILORED to the input, rather than a
 * fixed template. Items are included only when they apply: OAuth only when
 * authNeeded, the allowlist only for internal mode, access-control review only
 * when there are findings, and the DB items (connection string, the managed-PG
 * TLS footgun, the DigitalOcean trusted-sources binding) only when a database is
 * detected. NOTHING hard-blocks (blocking:false everywhere); all start unchecked.
 */
export function shipChecklist(input: WriteTodoInput): ChecklistItem[] {
  const mode = input.mode ?? "product";
  const databases = input.databases ?? [];
  const hasDb = databases.length > 0;
  const hasSqlDb = databases.some((d) => /postgres|mysql|maria/i.test(d));
  const hasFindings = (input.securityFollowups ?? []).length > 0;

  const items: ChecklistItem[] = [];
  const add = (id: string, label: string): void => {
    items.push({ id, label, done: false, blocking: false });
  };

  // Universal hygiene.
  add("rotate-secrets", "Rotate any secrets that were ever committed to git");

  // Auth: only when the app has (or should have) sign-in.
  if (input.authNeeded) {
    add(
      "register-oauth",
      "Register OAuth app(s) and paste CLIENT_ID/CLIENT_SECRET",
    );
  }

  // Allowlist: only for internal apps.
  if (mode === "internal") {
    add(
      "allowlist",
      "Confirm ALLOWED_EMAILS/ALLOWED_DOMAIN and lock the allowlist (internal mode)",
    );
  }

  // Access-control review: only when preflight actually surfaced findings.
  if (hasFindings) {
    add(
      "review-access-control",
      hasSqlDb
        ? "Review the access-control findings (and your Postgres RLS policies)"
        : "Review the access-control findings",
    );
  }

  // Database connectivity — the parts real deploys actually break on.
  if (hasDb) {
    add(
      "db-connection",
      "Confirm the pooled/private DB connection string is set in prod",
    );
    if (hasSqlDb) {
      add(
        "db-tls",
        "Verify the DB client handles managed-Postgres TLS (the sslmode / self-signed-CA footgun, e.g. node-postgres rejecting the CA)",
      );
    }
    if (input.target === "digitalocean") {
      add(
        "db-firewall",
        "Bind the managed DB to the app (a `databases:` section + `${db.DATABASE_URL}`) so DigitalOcean auto-manages trusted-sources — a raw DATABASE_URL secret leaves the firewall manual",
      );
    }
  }

  // Universal closers.
  add(
    "dependency-cve",
    "Run a dependency CVE check (e.g. `npm audit`) and apply upgrades",
  );
  add("custom-domain", "Set a custom domain (optional)");
  add("no-env-tracked", "Verify no .env is tracked in git");

  return items;
}

/**
 * renderTodoMarkdown - produce TODO.md with sections: "## Manual setup",
 * "## Security follow-ups", "## Ship checklist", "## Operate".
 */
export function renderTodoMarkdown(
  input: WriteTodoInput,
  checklist: ChecklistItem[],
): string {
  const mode = input.mode ?? "product";
  const out: string[] = [];

  out.push("# TODO");
  out.push("");
  out.push(
    "Generated by **Beam Me Up**. Nothing here hard-blocks your deploy, but " +
      "work through it to fully ship.",
  );
  out.push("");

  /* --- Manual setup ---------------------------------------------- */
  out.push("## Manual setup");
  out.push("");

  if (input.authNeeded) {
    out.push(
      "Auth is enabled for this app. Register an OAuth app with each provider " +
        "you want to support, set the redirect URI, then paste the credentials " +
        "into your environment as `<PROVIDER>_CLIENT_ID` / " +
        "`<PROVIDER>_CLIENT_SECRET`.",
    );
    out.push("");
    for (const provider of OAUTH_PROVIDERS) {
      const name = provider === "github" ? "GitHub" : "Google";
      out.push(`- [ ] Register a **${name}** OAuth app.`);
      out.push(
        `  - Set the redirect URI to \`${redirectUri(input.liveUrl, provider)}\`.`,
      );
      out.push(
        `  - Paste \`${provider.toUpperCase()}_CLIENT_ID\` and ` +
          `\`${provider.toUpperCase()}_CLIENT_SECRET\` into your env.`,
      );
    }
    out.push("");
  } else {
    out.push("No interactive auth is required for this app.");
    out.push("");
  }

  if (mode === "internal") {
    out.push(
      "- [ ] **Internal mode:** set `ALLOWED_EMAILS` and/or `ALLOWED_DOMAIN` " +
        "and lock the allowlist so only your team can sign in.",
    );
    out.push("");
  }

  const manualItems = input.manualItems ?? [];
  if (manualItems.length > 0) {
    for (const item of manualItems) {
      out.push(`- [ ] ${item}`);
    }
    out.push("");
  }

  /* --- Security follow-ups --------------------------------------- */
  out.push("## Security follow-ups");
  out.push("");
  const securityFollowups = input.securityFollowups ?? [];
  if (securityFollowups.length > 0) {
    for (const item of securityFollowups) {
      out.push(`- [ ] ${item}`);
    }
  } else {
    out.push("_No security follow-ups recorded._");
  }
  out.push("");

  /* --- Ship checklist -------------------------------------------- */
  out.push("## Ship checklist");
  out.push("");
  for (const item of checklist) {
    const box = item.done ? "x" : " ";
    const blockingTag = item.blocking ? " **(blocking)**" : "";
    out.push(`- [${box}] ${item.label}${blockingTag}`);
  }
  out.push("");

  /* --- Operate --------------------------------------------------- */
  out.push("## Operate");
  out.push("");

  if (input.target === "vercel") {
    out.push("- **View logs:** `vercel logs <deployment-url>` (or the Vercel dashboard -> your project -> Logs).");
    out.push("- **Redeploy:** push to your connected git branch, or run `vercel --prod`.");
    out.push("- **Manage env vars:** `vercel env` (or the dashboard -> Settings -> Environment Variables); redeploy to apply.");
  } else {
    out.push("- **View logs:** `doctl apps logs <app-id>` (or the DigitalOcean dashboard -> Apps -> your app -> Runtime Logs).");
    out.push("- **Redeploy:** push to your connected git branch, or run `doctl apps create-deployment <app-id>`.");
    out.push("- **Manage env vars:** edit the app spec / dashboard -> Settings -> App-Level Environment Variables; redeploy to apply.");
  }

  const databases = input.databases ?? [];
  if (databases.length > 0) {
    out.push("");
    out.push(
      `- **Database (${databases.join(", ")}) — two prod footguns:**`,
    );
    out.push(
      "  - **TLS:** managed Postgres often presents a self-signed CA, and a modern " +
        "`pg` client with `sslmode=require` can reject it (\"self-signed certificate " +
        "in certificate chain\"). Use the provider's CA cert, or set the client's " +
        "`ssl: { rejectUnauthorized: false }` (equivalently `sslmode=no-verify`).",
    );
    if (input.target === "digitalocean") {
      out.push(
        "  - **Firewall (trusted sources):** bind the managed DB as an app component " +
          "(`databases:` section + `${db.DATABASE_URL}`) so DigitalOcean auto-allows " +
          "the app. A raw `DATABASE_URL` secret leaves the cluster's trusted sources " +
          "manual — the app can't reach the DB until you add it by hand.",
      );
    }
  }

  if (input.liveUrl) {
    out.push("");
    out.push(`Live URL: ${input.liveUrl}`);
  }
  out.push("");

  return out.join("\n");
}
