import type { ChecklistItem, WriteTodoInput } from "@beam-me-up/core";

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

/** The OAuth providers we scaffold auth for (used in Manual setup). */
const OAUTH_PROVIDERS = ["google", "github"] as const;

/**
 * Build the OAuth redirect URI for a provider given the (best-known) live URL.
 * Falls back to a placeholder when liveUrl is not yet known.
 */
function redirectUri(liveUrl: string | undefined, provider: string): string {
  const base = (liveUrl ?? "<your-live-url>").replace(/\/+$/, "");
  return `${base}/api/auth/callback/${provider}`;
}

/**
 * shipChecklist - the standard ship-checklist items for the given input.
 *
 * Per the locked decision, NOTHING hard-blocks (blocking:false everywhere) and
 * all items start unchecked (done:false). Mode-sensitive labels (the allowlist
 * item) adapt to product vs internal.
 */
export function shipChecklist(input: WriteTodoInput): ChecklistItem[] {
  const mode = input.mode ?? "product";

  const allowlistLabel =
    mode === "internal"
      ? "Confirm ALLOWED_EMAILS/ALLOWED_DOMAIN for internal mode (lock the allowlist)"
      : "Confirm ALLOWED_EMAILS/ALLOWED_DOMAIN for the mode";

  const items: ChecklistItem[] = [
    {
      id: "rotate-secrets",
      label: "Rotate any committed secrets",
      done: false,
      blocking: false,
    },
    {
      id: "register-oauth",
      label: "Register OAuth app(s) and paste CLIENT_ID/CLIENT_SECRET",
      done: false,
      blocking: false,
    },
    {
      id: "allowlist",
      label: allowlistLabel,
      done: false,
      blocking: false,
    },
    {
      id: "review-access-control",
      label: "Review RLS / access-control findings",
      done: false,
      blocking: false,
    },
    {
      id: "apply-cve-upgrades",
      label: "Apply outstanding CVE upgrades",
      done: false,
      blocking: false,
    },
    {
      id: "custom-domain",
      label: "Set custom domain (optional)",
      done: false,
      blocking: false,
    },
    {
      id: "pooled-db-string",
      label: "Confirm pooled/private DB connection string in prod",
      done: false,
      blocking: false,
    },
    {
      id: "no-env-tracked",
      label: "Verify no .env is tracked in git",
      done: false,
      blocking: false,
    },
  ];

  return items;
}

/**
 * renderTodoMarkdown - produce TODO.md with sections: "## Manual setup",
 * "## Security follow-ups", "## Ship checklist", "## Operate".
 */
export function renderTodoMarkdown(
  input: WriteTodoInput,
  checklist: ChecklistItem[],
): string {
  const mode = input.mode ?? "product";
  const out: string[] = [];

  out.push("# TODO");
  out.push("");
  out.push(
    "Generated by **Beam Me Up**. Nothing here hard-blocks your deploy, but " +
      "work through it to fully ship.",
  );
  out.push("");

  /* --- Manual setup ---------------------------------------------- */
  out.push("## Manual setup");
  out.push("");

  if (input.authNeeded) {
    out.push(
      "Auth is enabled for this app. Register an OAuth app with each provider " +
        "you want to support, set the redirect URI, then paste the credentials " +
        "into your environment as `<PROVIDER>_CLIENT_ID` / " +
        "`<PROVIDER>_CLIENT_SECRET`.",
    );
    out.push("");
    for (const provider of OAUTH_PROVIDERS) {
      const name = provider === "github" ? "GitHub" : "Google";
      out.push(`- [ ] Register a **${name}** OAuth app.`);
      out.push(
        `  - Set the redirect URI to \`${redirectUri(input.liveUrl, provider)}\`.`,
      );
      out.push(
        `  - Paste \`${provider.toUpperCase()}_CLIENT_ID\` and ` +
          `\`${provider.toUpperCase()}_CLIENT_SECRET\` into your env.`,
      );
    }
    out.push("");
  } else {
    out.push("No interactive auth is required for this app.");
    out.push("");
  }

  if (mode === "internal") {
    out.push(
      "- [ ] **Internal mode:** set `ALLOWED_EMAILS` and/or `ALLOWED_DOMAIN` " +
        "and lock the allowlist so only your team can sign in.",
    );
    out.push("");
  }

  const manualItems = input.manualItems ?? [];
  if (manualItems.length > 0) {
    for (const item of manualItems) {
      out.push(`- [ ] ${item}`);
    }
    out.push("");
  }

  /* --- Security follow-ups --------------------------------------- */
  out.push("## Security follow-ups");
  out.push("");
  const securityFollowups = input.securityFollowups ?? [];
  if (securityFollowups.length > 0) {
    for (const item of securityFollowups) {
      out.push(`- [ ] ${item}`);
    }
  } else {
    out.push("_No security follow-ups recorded._");
  }
  out.push("");

  /* --- Ship checklist -------------------------------------------- */
  out.push("## Ship checklist");
  out.push("");
  for (const item of checklist) {
    const box = item.done ? "x" : " ";
    const blockingTag = item.blocking ? " **(blocking)**" : "";
    out.push(`- [${box}] ${item.label}${blockingTag}`);
  }
  out.push("");

  /* --- Operate --------------------------------------------------- */
  out.push("## Operate");
  out.push("");

  if (input.target === "vercel") {
    out.push("- **View logs:** `vercel logs <deployment-url>` (or the Vercel dashboard -> your project -> Logs).");
    out.push("- **Redeploy:** push to your connected git branch, or run `vercel --prod`.");
    out.push("- **Manage env vars:** `vercel env` (or the dashboard -> Settings -> Environment Variables); redeploy to apply.");
  } else {
    out.push("- **View logs:** `doctl apps logs <app-id>` (or the DigitalOcean dashboard -> Apps -> your app -> Runtime Logs).");
    out.push("- **Redeploy:** push to your connected git branch, or run `doctl apps create-deployment <app-id>`.");
    out.push("- **Manage env vars:** edit the app spec / dashboard -> Settings -> App-Level Environment Variables; redeploy to apply.");
  }

  if (input.liveUrl) {
    out.push("");
    out.push(`Live URL: ${input.liveUrl}`);
  }
  out.push("");

  return out.join("\n");
}
